// Path Catalog data
// ブラウザからの登録・読み込み・書き出しを推奨します。

window.PATH_CATALOG = [
  [
    "共通",
    [
      [
        "申請",
        [
          [
            "経費",
            [
              [
                "経費精算フォルダ",
                "\\\\fileserver\\share\\finance\\expense",
                "年度ごとに格納"
              ],
              [
                "旅費申請書式",
                "\\\\fileserver\\share\\finance\\travel\\forms",
                "出張手当含む"
              ]
            ]
          ],
          [
            "勤怠",
            [
              [
                "勤怠申請フォルダ",
                "\\\\fileserver\\share\\hr\\attendance",
                ""
              ],
              [
                "休暇申請テンプレート",
                "\\\\fileserver\\share\\hr\\leave\\template.docx",
                ""
              ]
            ]
          ],
          [
            "稟議",
            [
              [
                "稟議申請書式",
                "\\\\fileserver\\share\\admin\\ringi\\forms",
                "最新テンプレート"
              ],
              [
                "購買申請シート",
                "\\\\fileserver\\share\\procurement\\requests.xlsx",
                "月次締めあり"
              ]
            ]
          ]
        ]
      ],
      [
        "共有",
        [
          [
            "テンプレート",
            [
              [
                "議事録テンプレート",
                "\\\\fileserver\\share\\templates\\minutes.docx",
                ""
              ],
              [
                "契約書ドラフト",
                "\\\\fileserver\\share\\templates\\contract.docx",
                ""
              ]
            ]
          ],
          [
            "ガイド",
            [
              [
                "社内Wikiトップ",
                "https://wiki.example.local/",
                ""
              ],
              [
                "ブランドガイドライン",
                "\\\\fileserver\\share\\brand\\guide.pdf",
                ""
              ],
              [
                "ロゴ画像一式",
                "\\\\fileserver\\share\\brand\\logo",
                "SVG/PNG"
              ]
            ]
          ]
        ]
      ]
    ]
  ],
  [
    "業務",
    [
      [
        "設計",
        [
          [
            "API",
            [
              [
                "OpenAPI仕様書",
                "C:\\work\\spec\\openapi.yaml",
                ""
              ],
              [
                "APIモック",
                "\\\\fileserver\\share\\api\\mock",
                "sandbox"
              ]
            ]
          ],
          [
            "インフラ",
            [
              [
                "ネットワーク構成図",
                "\\\\fileserver\\share\\infra\\nw-diagram.drawio",
                ""
              ],
              [
                "IaCテンプレート",
                "C:\\work\\infra\\terraform\\modules",
                ""
              ]
            ]
          ],
          [
            "DB",
            [
              [
                "ER図",
                "\\\\fileserver\\share\\db\\er\\main.drawio",
                "最新版"
              ],
              [
                "マイグレーションスクリプト",
                "\\\\fileserver\\share\\db\\migration",
                ""
              ]
            ]
          ]
        ]
      ],
      [
        "開発",
        [
          [
            "リポジトリ",
            [
              [
                "Monorepo",
                "C:\\dev\\repo\\monorepo",
                ""
              ],
              [
                "Design System Repo",
                "C:\\dev\\repo\\design-system",
                ""
              ]
            ]
          ],
          [
            "ビルド",
            [
              [
                "CI設定",
                "\\\\fileserver\\share\\ci\\pipelines",
                "共通ジョブ"
              ],
              [
                "パイプラインテンプレ",
                "\\\\fileserver\\share\\ci\\templates",
                ""
              ]
            ]
          ],
          [
            "ツール",
            [
              [
                "コードスタイル設定",
                "C:\\dev\\config\\lint\\.eslintrc.json",
                ""
              ],
              [
                "npm private registry",
                "https://npm.example.local/",
                ""
              ]
            ]
          ]
        ]
      ],
      [
        "運用",
        [
          [
            "ジョブ",
            [
              [
                "夜間バッチ",
                "\\\\fileserver\\share\\ops\\batch\\nightly",
                ""
              ],
              [
                "月次集計ジョブ",
                "\\\\fileserver\\share\\ops\\batch\\monthly",
                ""
              ]
            ]
          ],
          [
            "監視",
            [
              [
                "監視ダッシュボードURL",
                "https://monitor.example.local/dashboards/main",
                ""
              ],
              [
                "アラート設定",
                "\\\\fileserver\\share\\ops\\monitoring\\alerts",
                ""
              ]
            ]
          ],
          [
            "障害対応",
            [
              [
                "インシデント手順書",
                "\\\\fileserver\\share\\ops\\incident\\runbook.pdf",
                ""
              ],
              [
                "バックアップ",
                "\\\\fileserver\\share\\backup\\db",
                "日次"
              ]
            ]
          ]
        ]
      ],
      [
        "顧客",
        [
          [
            "案件共通",
            [
              [
                "NDA雛形",
                "\\\\fileserver\\share\\clients\\common\\nda.docx",
                ""
              ],
              [
                "契約基本書",
                "\\\\fileserver\\share\\clients\\common\\msa.docx",
                ""
              ]
            ]
          ],
          [
            "案件A",
            [
              [
                "案件A仕様書",
                "\\\\fileserver\\share\\clients\\a\\spec",
                ""
              ],
              [
                "案件A納品物",
                "\\\\fileserver\\share\\clients\\a\\deliverables",
                ""
              ]
            ]
          ],
          [
            "案件B",
            [
              [
                "案件B仕様書",
                "\\\\fileserver\\share\\clients\\b\\spec",
                ""
              ],
              [
                "案件B納品物",
                "\\\\fileserver\\share\\clients\\b\\deliverables",
                ""
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];
